// Generated by Selenium IDE
import { Builder, By, Key, until, WebDriver } from 'selenium-webdriver';
import assert from 'assert';
import Mocha from 'mocha';
import firefox from 'selenium-webdriver/firefox.js';
import { Select } from 'selenium-webdriver/lib/select.js'

async function selectByText(
  driver: WebDriver,
  selectLocator: By,
  text: string
) {
  const selectEl = await driver.wait(
    until.elementLocated(selectLocator),
    20000
  )
  const select = new Select(selectEl)
  await select.selectByVisibleText(text)
}

describe('Recetas', function(this: Mocha.Suite) {
  this.timeout(600000)
  let driver: WebDriver
  let vars

  const options = new firefox.Options();
  options.addArguments('-headless');

  beforeEach(async function() {
    driver = await new Builder()
    .forBrowser('firefox')
    .setFirefoxOptions(options)
    .build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })

  it('Renderización de receta propia', async function() {
    await driver.get("http://localhost:5173/login")
    await driver.manage().window().setRect({ width: 1500, height: 904 })
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("elena.sanchez@test.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("Password123!")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    await driver.get("http://localhost:5173/recipe/000000000000000000000021")
    const h2 = await driver.wait(
      until.elementLocated(By.css("h2")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(h2),
      20000
    )
    assert(await h2.getText() == "Gazpacho Andaluz")
    {
      const elements = await driver.findElements(By.css(".profile-link > .foto-perfil-grande"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".post-user-name")).getText() == "ChefElenaES")
    {
      const elements = await driver.findElements(By.css(".boton-control-receta > button:nth-child(1)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".boton-control-receta > button:nth-child(2)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".lucide-star"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".rating-pill > p")).getText() == "-")
    assert(await driver.findElement(By.css(".CategoriasReceta > h3")).getText() == "Categorías")
    {
      const elements = await driver.findElements(By.css(".category-tag:nth-child(1)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".category-tag:nth-child(2)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".category-tag:nth-child(3)"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".IngredientesReceta > h3")).getText() == "Ingredientes")
    assert(await driver.findElement(By.css(".IngredientesReceta li:nth-child(1)")).getText() == "aceite: 100ml")
    assert(await driver.findElement(By.css(".IngredientesReceta li:nth-child(2)")).getText() == "sal: 1 pizca")
    assert(await driver.findElement(By.css(".UtensiliosReceta > h3")).getText() == "Utensilios")
    console.log(await driver.findElement(By.css(".UtensiliosReceta li:nth-child(1)")).getText() + "1")
    const text = await driver.executeScript(
      "return arguments[0].textContent",
      await driver.findElement(By.css(".UtensiliosReceta li:nth-child(1)"))
    ) as string

    assert.strictEqual(text.trim(), "cuchillo")
    const text1 = await driver.executeScript(
      "return arguments[0].textContent",
      await driver.findElement(By.css(".UtensiliosReceta li:nth-child(2)"))
    ) as string

    assert.strictEqual(text1.trim(), "batidora")
    {
      const elements = await driver.findElements(By.css(".carousel-media > img"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".right-btn"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".left-btn"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".active-dot"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".TextoReceta > h3")).getText() == "Receta")
    assert(await driver.findElement(By.css(".TextoReceta > p")).getText() == "Triturar tomates, pepino, pimiento, pan, aceite y vinagre. Servir frío.")
    const container = await driver.findElement(By.css(".ContenedorReceta"));

    await driver.executeScript(
    "arguments[0].scrollTop = arguments[0].scrollHeight",
    container
    );
    assert(await driver.findElement(By.css(".ResenasReceta > h3")).getText() == "Reseñas")
    assert(await driver.findElement(By.css(".ResenasReceta > p")).getText() == "Todavía no hay reseñas para esta receta.")
  })
  it('Edición correcta de receta', async function() {
    await driver.get("http://localhost:5173/login")
    await driver.manage().window().setRect({ width: 1500, height: 904 })
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("elena.sanchez@test.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("Password123!")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    await driver.get("http://localhost:5173/recipe/000000000000000000000021")
    const h2 = await driver.wait(
      until.elementLocated(By.css("h2")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(h2),
      20000
    )
    assert(await driver.findElement(By.css("h2")).getText() == "Gazpacho Andaluz")
    {
      const elements = await driver.findElements(By.css(".profile-link > .foto-perfil-grande"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".post-user-name")).getText() == "ChefElenaES")
    {
      const elements = await driver.findElements(By.css(".boton-control-receta > button:nth-child(1)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".boton-control-receta > button:nth-child(2)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".lucide-star"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".rating-pill > p")).getText() == "-")
    assert(await driver.findElement(By.css(".CategoriasReceta > h3")).getText() == "Categorías")
    {
      const elements = await driver.findElements(By.css(".category-tag:nth-child(1)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".category-tag:nth-child(2)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".category-tag:nth-child(3)"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".IngredientesReceta > h3")).getText() == "Ingredientes")
    assert(await driver.findElement(By.css(".IngredientesReceta li:nth-child(1)")).getText() == "aceite: 100ml")
    assert(await driver.findElement(By.css(".IngredientesReceta li:nth-child(2)")).getText() == "sal: 1 pizca")
    assert(await driver.findElement(By.css(".UtensiliosReceta > h3")).getText() == "Utensilios")
    const text1 = await driver.executeScript(
      "return arguments[0].textContent",
      await driver.findElement(By.css(".UtensiliosReceta li:nth-child(1)"))
    ) as string

    assert.strictEqual(text1.trim(), "cuchillo")
    const text2 = await driver.executeScript(
      "return arguments[0].textContent",
      await driver.findElement(By.css(".UtensiliosReceta li:nth-child(2)"))
    ) as string

    assert.strictEqual(text2.trim(), "batidora")
    {
      const elements = await driver.findElements(By.css(".carousel-media > img"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".right-btn"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".left-btn"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".active-dot"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".TextoReceta > h3")).getText() == "Receta")
    assert(await driver.findElement(By.css(".TextoReceta > p")).getText() == "Triturar tomates, pepino, pimiento, pan, aceite y vinagre. Servir frío.")
    const container = await driver.findElement(By.css(".ContenedorReceta"));

    await driver.executeScript(
    "arguments[0].scrollTop = arguments[0].scrollHeight",
    container
    );
    assert(await driver.findElement(By.css(".ResenasReceta > h3")).getText() == "Reseñas")
    assert(await driver.findElement(By.css(".ResenasReceta > p")).getText() == "Todavía no hay reseñas para esta receta.")
    await driver.findElement(By.css(".boton-control-receta > button:nth-child(1)")).click()
    await driver.findElement(By.name("category[0]")).click()
    {
      const dropdown = await driver.findElement(By.name("category[0]"))
      await dropdown.findElement(By.xpath("//option[. = 'plato principal']")).click()
    }
    await driver.findElement(By.css(".filaCategorias:nth-child(1) option:nth-child(3)")).click()
    await driver.findElement(By.name("ingredients[0].ingredient")).click()
    {
      const dropdown = await driver.findElement(By.name("ingredients[0].ingredient"))
      await dropdown.findElement(By.xpath("//option[. = 'vainilla']")).click()
    }
    await driver.findElement(By.css(".filaIngrediente:nth-child(1) option:nth-child(11)")).click()
    await driver.findElement(By.name("ingredients[0].quantity")).click()
    await driver.findElement(By.name("ingredients[0].quantity")).clear()
    await driver.findElement(By.name("ingredients[0].quantity")).sendKeys("1100ml")
    await driver.findElement(By.name("tools[0]")).click()
    {
      const dropdown = await driver.findElement(By.name("tools[0]"))
      await dropdown.findElement(By.xpath("//option[. = 'tabla de cortar']")).click()
    }
    await driver.findElement(By.css(".filaUtensilio:nth-child(1) option:nth-child(3)")).click()
    await driver.findElement(By.id("steps")).click()
    await driver.findElement(By.id("steps")).clear()
    await driver.findElement(By.id("steps")).sendKeys("Triturar tomates, pepino, pimiento, pan, aceite y vinagre. Servir frío.A")
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).clear()
    await driver.findElement(By.id("name")).sendKeys("Gazpacho AndaluzA")
    await driver.findElement(By.css(".botonPublicar")).click()
    assert(await driver.findElement(By.css(".IngredientesReceta li:nth-child(1)")).getText() == "vainilla: 1100ml")
    const text3 = await driver.executeScript(
      "return arguments[0].textContent",
      await driver.findElement(By.css(".UtensiliosReceta li:nth-child(1)"))
    ) as string

    assert.strictEqual(text3.trim(), "tabla de cortar")
    assert(await driver.findElement(By.css("h2")).getText() == "Gazpacho AndaluzA")
    assert(await driver.findElement(By.css(".TextoReceta > p")).getText() == "Triturar tomates, pepino, pimiento, pan, aceite y vinagre. Servir frío.A")
    await driver.findElement(By.css(".boton-panel:nth-child(3)")).click()
    const text5 = await driver.executeScript(
      "return arguments[0].textContent",
      await driver.findElement(By.css(".post-title"))
    ) as string

    assert.strictEqual(text5.trim(), "Gazpacho AndaluzA")
    await driver.get("http://localhost:5173/recipe/000000000000000000000021")
    const boton = await driver.wait(
      until.elementLocated(By.css(".boton-control-receta > button:nth-child(1)")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(boton),
      20000
    )
    await boton.click()
    await driver.findElement(By.name("category[0]")).click()
    {
      const dropdown = await driver.findElement(By.name("category[0]"))
      await dropdown.findElement(By.xpath("//option[. = 'entrante']")).click()
    }
    await driver.findElement(By.css(".filaCategorias:nth-child(1) option:nth-child(2)")).click()
    await driver.findElement(By.name("ingredients[0].ingredient")).click()
    {
      const dropdown = await driver.findElement(By.name("ingredients[0].ingredient"))
      await dropdown.findElement(By.xpath("//option[. = 'aceite']")).click()
    }
    await driver.findElement(By.css(".filaIngrediente:nth-child(1) option:nth-child(8)")).click()
    await driver.findElement(By.name("ingredients[0].quantity")).click()
    await driver.findElement(By.name("ingredients[0].quantity")).clear()
    await driver.findElement(By.name("ingredients[0].quantity")).sendKeys("100ml")
    await driver.findElement(By.name("tools[0]")).click()
    {
      const dropdown = await driver.findElement(By.name("tools[0]"))
      await dropdown.findElement(By.xpath("//option[. = 'cuchillo']")).click()
    }
    await driver.findElement(By.css(".filaUtensilio:nth-child(1) option:nth-child(2)")).click()
    await driver.findElement(By.id("steps")).click()
    await driver.findElement(By.id("steps")).clear()
    await driver.findElement(By.id("steps")).sendKeys("Triturar tomates, pepino, pimiento, pan, aceite y vinagre. Servir frío.")
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).clear()
    await driver.findElement(By.id("name")).sendKeys("Gazpacho Andaluz")
    await driver.findElement(By.css(".botonPublicar")).click()
    assert(await driver.findElement(By.css(".IngredientesReceta li:nth-child(1)")).getText() == "aceite: 100ml")
    assert(await driver.findElement(By.css("h2")).getText() == "Gazpacho Andaluz")
    const text4 = await driver.executeScript(
      "return arguments[0].textContent",
      await driver.findElement(By.css(".UtensiliosReceta li:nth-child(1)"))
    ) as string

    assert.strictEqual(text4.trim(), "cuchillo")
    assert(await driver.findElement(By.css(".TextoReceta > p")).getText() == "Triturar tomates, pepino, pimiento, pan, aceite y vinagre. Servir frío.")
  })
  it('Edición incorrecta de receta', async function() {
    await driver.get("http://localhost:5173/login")
    await driver.manage().window().setRect({ width: 1500, height: 904 })
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("elena.sanchez@test.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("Password123!")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    await driver.get("http://localhost:5173/recipe/000000000000000000000021")
    const h2 = await driver.wait(
      until.elementLocated(By.css("h2")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(h2),
      20000
    )
    await driver.findElement(By.css(".boton-control-receta > button:nth-child(1)")).click()
    await driver.findElement(By.css(".CategoriaPublicacion > .botonMasGeneral")).click()
    await driver.findElement(By.name("category[3]")).click()
    await driver.findElement(By.css(".CategoriaPublicacion")).click()
    assert(await driver.findElement(By.css(".help")).getText() == "Seleccione una categoría")
    await driver.findElement(By.name("category[3]")).click()
    {
      const dropdown = await driver.findElement(By.name("category[3]"))
      await dropdown.findElement(By.xpath("//option[. = 'entrante']")).click()
    }
    await driver.findElement(By.css(".filaCategorias:nth-child(4) option:nth-child(2)")).click()
    assert(await driver.findElement(By.css(".help")).getText() == "No puede haber categorías duplicadas")
    await driver.findElement(By.css(".filaCategorias:nth-child(4) .lucide")).click()
    {
      const elements = await driver.findElements(By.css(".help"))
      assert(!elements.length)
    }
    await driver.findElement(By.css(".IngredientesReceta > .botonMasGeneral")).click()
    await driver.findElement(By.name("ingredients[2].ingredient")).click()
    await driver.findElement(By.css(".IngredientesReceta")).click()
    await driver.findElement(By.name("ingredients[2].quantity")).click()
    await driver.findElement(By.css(".listaIngredientes")).click()
    assert(await driver.findElement(By.css(".help:nth-child(4)")).getText() == "Seleccione un ingrediente")
    assert(await driver.findElement(By.css(".help:nth-child(5)")).getText() == "Introduzca una cantidad")
    await driver.findElement(By.name("ingredients[2].ingredient")).click()
    {
      const dropdown = await driver.findElement(By.name("ingredients[2].ingredient"))
      await dropdown.findElement(By.xpath("//option[. = 'aceite']")).click()
    }
    await driver.findElement(By.css(".filaIngrediente:nth-child(3) option:nth-child(8)")).click()
    await driver.findElement(By.name("ingredients[2].quantity")).click()
    await driver.findElement(By.name("ingredients[2].quantity")).sendKeys("13g")
    await driver.findElement(By.css(".IngredientesReceta")).click()
    assert(await driver.findElement(By.css(".help")).getText() == "No puede haber ingredientes duplicados")
    await driver.findElement(By.name("ingredients[2].ingredient")).click()
    await selectByText(driver, By.name("ingredients[2].ingredient"), "frutas")
    {
      const elements = await driver.findElements(By.css(".help"))
      assert(!elements.length)
    }
    await driver.findElement(By.css(".UtensiliosReceta > .botonMasGeneral")).click()
    await driver.findElement(By.name("tools[2]")).click()
    await driver.findElement(By.css(".InformacionPublicacion")).click()
    assert(await driver.findElement(By.css(".help")).getText() == "Seleccione un utensilio")
    await driver.findElement(By.name("tools[2]")).click()
    {
      const dropdown = await driver.findElement(By.name("tools[2]"))
      await dropdown.findElement(By.xpath("//option[. = 'cuchillo']")).click()
    }
    await driver.findElement(By.css(".filaUtensilio:nth-child(3) option:nth-child(2)")).click()
    assert(await driver.findElement(By.css(".help")).getText() == "No puede haber utensilios duplicados")
    await driver.findElement(By.name("tools[2]")).click()
    await selectByText(driver, By.name("tools[2]"), "rallador")
    await driver.wait(async () => {
      const elements = await driver.findElements(By.css(".help"))
      return elements.length === 0
    }, 30000)
    {
      const elements = await driver.findElements(By.css(".help"))
      assert(!elements.length)
    }
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).clear()
    await driver.findElement(By.id("steps")).click()
    assert(await driver.findElement(By.css(".NombreReceta > .help")).getText() == "Se necesita poner un nombre a la receta")
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("Ga")
    await driver.findElement(By.css(".NombreReceta")).click()
    await driver.findElement(By.id("steps")).click()
    await driver.findElement(By.css(".TextoPublicacion > h3")).click()
    assert(await driver.findElement(By.css(".NombreReceta > .help")).getText() == "El nombre de la receta debe de tener al menos 6 caracteres")
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("Gafdjakfdjafdjahndajvhjnfjdanhfdajhvbafdjvbffjavbjfhnadbhfad")
    await driver.findElement(By.id("steps")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".TextoPublicacion > h3")).click()
    assert(await driver.findElement(By.css(".NombreReceta > .help")).getText() == "El nombre de la receta no puede tener más de 50 caracteres")
    await driver.findElement(By.id("name")).clear()
    await driver.findElement(By.id("name")).sendKeys("Gazpacho Andaluz")
    await driver.wait(async () => {
      const elements = await driver.findElements(By.css(".NombreReceta > .help"))
      return elements.length === 0
    }, 30000)
    {
      const elements = await driver.findElements(By.css(".NombreReceta > .help"))
      assert(!elements.length)
    }
  })
  it('Publicación, edición y borrado de reseña ', async function() {
    await driver.get("http://localhost:5173/login")
    await driver.manage().window().setRect({ width: 1500, height: 904 })
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("elena.sanchez@test.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("Password123!")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    await driver.get("http://localhost:5173/recipe/000000000000000000000022")
    const h2 = await driver.wait(
      until.elementLocated(By.css("h2")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(h2),
      20000
    )
    await driver.findElement(By.css(".boton-resena-salmon")).click()
    assert(await driver.findElement(By.css(".form-group:nth-child(1) > .form-label")).getText() == "Valoración")
    const container = await driver.findElement(By.css(".ContenedorReceta"));

    await driver.executeScript(
    "arguments[0].scrollTop = arguments[0].scrollHeight",
    container
    );
    assert(await driver.findElement(By.css(".form-group:nth-child(2) > .form-label")).getText() == "Tu comentario")
    {
      const elements = await driver.findElements(By.name("rating"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.name("text"))
      assert(elements.length)
    }
    await driver.findElement(By.name("rating")).click()
    await selectByText(driver, By.name("rating"), "3 estrellas")
    await driver.findElement(By.name("text")).click()
    await driver.findElement(By.name("text")).sendKeys("Reseña.")
    await driver.findElement(By.css(".boton-resena-salmon")).click()
    {
      const elements = await driver.findElements(By.css(".resena-card"))
      assert(elements.length)
    }
    await driver.executeScript("window.scrollTo(0,60)")
    {
      const elements = await driver.findElements(By.css(".resena-card"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".resena-avatar"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".resena-username")).getText() == "ChefElenaES")
    {
      const elements = await driver.findElements(By.css(".estrella-salmon-icon > path"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".rating-pill:nth-child(2) > p")).getText() == "3")
    {
      const elements = await driver.findElements(By.css(".textoResena"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".editar"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".borrar"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".boton-resena-salmon"))
      assert(!elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".ResenasReceta > p"))
      assert(!elements.length)
    }
    await driver.findElement(By.css(".editar")).click()
    await driver.findElement(By.name("rating")).click()
    await selectByText(driver, By.name("rating"), "2 estrellas")
    await driver.findElement(By.name("text")).click()
    await driver.findElement(By.name("text")).sendKeys("Reseña editada.")
    await driver.findElement(By.css(".boton-cancelar")).click()
    await driver.findElement(By.css(".editar")).click()
    await driver.findElement(By.name("rating")).click()
    await selectByText(driver, By.name("rating"), "2 estrellas")
    await driver.findElement(By.name("text")).click()
    await driver.findElement(By.name("text")).clear()
    await driver.findElement(By.name("text")).sendKeys("Reseña editada.")
    await driver.findElement(By.css(".boton-resena-salmon")).click()
    assert(await driver.findElement(By.css(".rating-pill > p")).getText() == "2.0")
    await driver.executeScript(
    "arguments[0].scrollTop = arguments[0].scrollHeight",
    container
    );
    assert(await driver.findElement(By.css(".textoResena")).getText() == "Reseña editada.")
    await driver.findElement(By.css(".logout")).click()
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("sophie.legrand@test.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("Password123!")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    await driver.get("http://localhost:5173/recipe/000000000000000000000022")
    const h21 = await driver.wait(
      until.elementLocated(By.css("h2")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(h21),
      20000
    )
    await driver.findElement(By.css(".boton-resena-salmon")).click()
    await driver.findElement(By.name("rating")).click()
    await selectByText(driver, By.name("rating"), "5 estrellas")
    await driver.findElement(By.name("text")).click()
    await driver.findElement(By.name("text")).sendKeys("Muy buena.")
    await driver.findElement(By.css(".boton-resena-salmon")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    assert(await driver.findElement(By.css(".rating-pill > p")).getText() == "3.5")
    {
      const elements = await driver.findElements(By.css(".contenedorResena:nth-child(3) > button:nth-child(1)"))
      assert(!elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".contenedorResena:nth-child(3) > button:nth-child(2)"))
      assert(!elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".editar"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".borrar"))
      assert(elements.length)
    }
    await driver.findElement(By.css(".borrar")).click()
    assert(await driver.switchTo().alert().getText() == "¿Borrar reseña?")
    await driver.switchTo().alert().accept()
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".rating-pill > p")), '2.0'), 30000)
    const text = await driver.executeScript(
      "return arguments[0].textContent",
      await driver.findElement(By.css(".rating-pill > p"))
    ) as string

    assert.strictEqual(text.trim(), "2.0")
    await driver.findElement(By.css(".logout")).click()
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("elena.sanchez@test.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("Password123!")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    await driver.get("http://localhost:5173/recipe/000000000000000000000022")
    const h22 = await driver.wait(
      until.elementLocated(By.css("h2")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(h22),
      20000
    )
    const container1 = await driver.findElement(By.css(".ContenedorReceta"));

    await driver.executeScript(
    "arguments[0].scrollTop = arguments[0].scrollHeight",
    container1
    );
    await driver.findElement(By.css(".borrar")).click()
    assert(await driver.switchTo().alert().getText() == "¿Borrar reseña?")
    await driver.switchTo().alert().accept()
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".rating-pill > p")), '-'), 30000)
    const text3 = await driver.executeScript(
      "return arguments[0].textContent",
      await driver.findElement(By.css(".rating-pill > p"))
    ) as string

    assert.strictEqual(text3.trim(), "-")
    {
      const elements = await driver.findElements(By.css(".boton-resena-salmon"))
      assert(elements.length)
    }
  })
  it('Renderización de receta ajena', async function() {
    await driver.get("http://localhost:5173/login")
    await driver.manage().window().setRect({ width: 1500, height: 904 })
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("elena.sanchez@test.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("Password123!")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    await driver.get("http://localhost:5173/recipe/000000000000000000000022")
    const h2 = await driver.wait(
      until.elementLocated(By.css("h2")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(h2),
      20000
    )
    assert(await driver.findElement(By.css("h2")).getText() == "Pasta Cacio e Pepe")
    {
      const elements = await driver.findElements(By.css(".profile-link > .foto-perfil-grande"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".post-user-name")).getText() == "ItalianoCucina")
    {
      const elements = await driver.findElements(By.css(".boton-control-receta > button:nth-child(1)"))
      assert(!elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".boton-control-receta > button:nth-child(2)"))
      assert(!elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".lucide-star"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".rating-pill > p")).getText() == "-")
    {
      const elements = await driver.findElements(By.css(".post-save-button-inner"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".CategoriasReceta > h3")).getText() == "Categorías")
    {
      const elements = await driver.findElements(By.css(".category-tag:nth-child(1)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".category-tag:nth-child(2)"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".IngredientesReceta > h3")).getText() == "Ingredientes")
    assert(await driver.findElement(By.css(".IngredientesReceta li:nth-child(1)")).getText() == "aceite: 50ml")
    assert(await driver.findElement(By.css(".IngredientesReceta li:nth-child(2)")).getText() == "sal: 1 pizca")
    assert(await driver.findElement(By.css(".UtensiliosReceta > h3")).getText() == "Utensilios")
    const text = await driver.executeScript(
      "return arguments[0].textContent",
      await driver.findElement(By.css(".UtensiliosReceta li:nth-child(1)"))
    ) as string

    assert.strictEqual(text.trim(), "olla")
    {
      const elements = await driver.findElements(By.css(".carousel-media > img"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".right-btn"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".left-btn"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".active-dot"))
      assert(elements.length)
    }
    const text1 = await driver.executeScript(
      "return arguments[0].textContent",
      await driver.findElement(By.css(".TextoReceta > h3"))
    ) as string

    assert.strictEqual(text1.trim(), "Receta")
    const text2 = await driver.executeScript(
      "return arguments[0].textContent",
      await driver.findElement(By.css(".TextoReceta > p"))
    ) as string

    assert.strictEqual(text2.trim(), "Hervir pasta. Mezclar queso Pecorino y pimienta con agua de cocción para crear salsa.")
    assert(await driver.findElement(By.css(".ResenasReceta > h3")).getText() == "Reseñas")
    assert(await driver.findElement(By.css(".ResenasReceta > p")).getText() == "Todavía no hay reseñas para esta receta. ¡Sé el primero en compartir la tuya!")
    {
      const elements = await driver.findElements(By.css(".boton-resena-salmon"))
      assert(elements.length)
    }
  })
})