// Generated by Selenium IDE
import { Builder, By, Key, until, WebDriver } from 'selenium-webdriver';
import assert from 'assert';
import Mocha from 'mocha';
import firefox from 'selenium-webdriver/firefox.js';
import { Select } from 'selenium-webdriver/lib/select.js'

async function selectByText(
  driver: WebDriver,
  selectLocator: By,
  text: string
) {
  const selectEl = await driver.wait(
    until.elementLocated(selectLocator),
    20000
  )
  const select = new Select(selectEl)
  await select.selectByVisibleText(text)
}
//test de log-in correcto
describe('Inicio', function(this: Mocha.Suite) {
  this.timeout(600000)
  let driver: WebDriver
  let vars

  const options = new firefox.Options();
  options.addArguments('-headless');

  beforeEach(async function() {
    driver = await new Builder()
    .forBrowser('firefox')
    .setFirefoxOptions(options)
    .build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })

  //test de log-in correcto
  it('Renderizacion correcta', async function() {
    await driver.get("http://localhost:5173/login")
    await driver.manage().window().setRect({ width: 1181, height: 902 })
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("elena.sanchez@test.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("Password123!")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    assert(await driver.findElement(By.css(".section-title")).getText() == "Posts")
    {
      const elements = await driver.findElements(By.css(".tarjeta:nth-child(1)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".tarjeta:nth-child(1) .imagen-post"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".tarjeta:nth-child(1) .post-user-name"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".tarjeta:nth-child(1) .stat-item:nth-child(1)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".tarjeta:nth-child(1) .stat-item:nth-child(3)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".tarjeta:nth-child(1) .category-tag:nth-child(1)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".tarjeta:nth-child(1) .post-title"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".tarjeta:nth-child(2)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".tarjeta:nth-child(3)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".tarjeta:nth-child(4)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".tarjeta:nth-child(5)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".tarjeta:nth-child(6)"))
      assert(elements.length)
    }
    await driver.findElement(By.css(".tarjeta:nth-child(1) .post-title")).click()
    const h3 = await driver.wait(
      until.elementLocated(By.css(".CategoriasReceta > h3")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(h3),
      20000
    )
    assert(await h3.getText() == "Categorías")
    await driver.get("http://localhost:5173/home")
    const title = await driver.wait(
      until.elementLocated(By.css(".section-title")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(title),
      20000
    )
    assert(await title.getText() == "Posts")
    {
      const elements = await driver.findElements(By.css(".active"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".boton-panel:nth-child(2)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".boton-panel:nth-child(3)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".boton-panel:nth-child(4)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".boton-panel:nth-child(5)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".logout"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".recipe-vault-logo"))
      assert(elements.length)
    }
    await driver.findElement(By.css(".logout")).click()
    assert(await driver.getTitle() == "Log-In / RecipeVault")
  })
})