// Generated by Selenium IDE
import { Builder, By, Key, until, WebDriver } from 'selenium-webdriver';
import assert from 'assert';
import Mocha from 'mocha';
import firefox from 'selenium-webdriver/firefox.js';
import { Select } from 'selenium-webdriver/lib/select.js'

async function selectByText(
  driver: WebDriver,
  selectLocator: By,
  text: string
) {
  const selectEl = await driver.wait(
    until.elementLocated(selectLocator),
    20000
  )
  const select = new Select(selectEl)
  await select.selectByVisibleText(text)
}

//test de log-in correcto
describe('LogIn', function(this: Mocha.Suite) {
  this.timeout(600000)
  let driver: WebDriver
  let vars

  const options = new firefox.Options();
  options.addArguments('-headless');

  beforeEach(async function() {
    driver = await new Builder()
    .forBrowser('firefox')
    .setFirefoxOptions(options)
    .build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  //test de log-in correcto
  it('Log-in correcto', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    assert(await driver.getTitle() == "Log-In / RecipeVault")
    {
      const elements = await driver.findElements(By.css(".Logo > img"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".InicioRegistro:nth-child(2) > h1"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".InicioRegistro:nth-child(4) > h1"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".InicioRegistro:nth-child(2) > form"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".InicioRegistro:nth-child(4) > form"))
      assert(elements.length)
    }
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("elena.sanchez@test.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("Password123!")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    assert(await driver.findElement(By.css(".section-title")).getText() == "Posts")
    {
      const elements = await driver.findElements(By.css(".foto-perfil-grande"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".user-name")).getText() == "ChefElenaES")
    assert(await driver.findElement(By.css(".user-handle")).getText() == "@chefelenaes")
    assert(await driver.findElement(By.css("div:nth-child(1) > .stat-number")).getText() == "1")
    assert(await driver.findElement(By.css("div:nth-child(2) > .stat-number")).getText() == "0")
    assert(await driver.findElement(By.css("div:nth-child(3) > .stat-number")).getText() == "0")
    assert(await driver.findElement(By.css("div:nth-child(1) > .stat-label")).getText() == "Posts")
    assert(await driver.findElement(By.css("div:nth-child(2) > .stat-label")).getText() == "Seguidores")
    assert(await driver.findElement(By.css("div:nth-child(3) > .stat-label")).getText() == "Seguidos")
    assert(await driver.findElement(By.css(".user-description")).getText() == "Especialista en tapas y arroces.")
  })
  //test de log-in con campos erróneos
  it('Log-in con campos erróneos', async function() {
    await driver.get("http://localhost:5173/")
    assert(await driver.getTitle() == "Log-In / RecipeVault")
    await driver.manage().window().setRect({ width: 1181, height: 897 })
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lpassword")).click()
    assert(await driver.findElement(By.css(".help")).getText() == "El email es obligatorio")
    await driver.findElement(By.id("lemail")).click()
    assert(await driver.findElement(By.css(".help:nth-child(10)")).getText() == "La contraseña es obligatoria")
    await driver.findElement(By.id("lemail")).sendKeys("aaaaaa")
    assert(await driver.findElement(By.css(".InicioRegistro:nth-child(2) .help:nth-child(5)")).getText() == "Debe de ser un email")
    await driver.findElement(By.id("lpassword")).sendKeys("aaa")
    assert(await driver.findElement(By.css(".help:nth-child(10)")).getText() == "La contraseña debe de tener al menos 6 caracteres")
    await driver.findElement(By.css(".submit:nth-child(11)")).click()
    assert(await driver.getTitle() == "Log-In / RecipeVault")
    await driver.findElement(By.id("lpassword")).sendKeys("aaaaaaa")
    {
      const elements = await driver.findElements(By.css(".help:nth-child(10)"))
      assert(!elements.length)
    }
    await driver.findElement(By.id("lemail")).sendKeys("email@gmail.com")
    {
      const elements = await driver.findElements(By.css(".InicioRegistro:nth-child(2) .help:nth-child(5)"))
      assert(!elements.length)
    }
  })
  //test de log-in con contraseña incorrecta
  it('Log-in con contraseña incorrecta', async function() {
    await driver.get("http://localhost:5173/")
    assert(await driver.getTitle() == "Log-In / RecipeVault")
    await driver.manage().window().setRect({ width: 1181, height: 897 })
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("elena.sanchez@test.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("oooooooo")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    assert(await driver.findElement(By.css(".error-message")).getText() == "El usuario o la contraseña son incorrectos")
    assert(await driver.getTitle() == "Log-In / RecipeVault")
  })
  //test de log-in con usuario incorrecto
  it('Log-in con usuario incorrecto', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1181, height: 897 })
    assert(await driver.getTitle() == "Log-In / RecipeVault")
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("oooooooo@gmail.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("oooooooo")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    assert(await driver.findElement(By.css(".error-message")).getText() == "El usuario o la contraseña son incorrectos")
    assert(await driver.getTitle() == "Log-In / RecipeVault")
  })
  //test de sign-up con campos erróneos
  it('Sign-up con campos erróneos', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1181, height: 897 })
    assert(await driver.getTitle() == "Log-In / RecipeVault")
    await driver.findElement(By.id("ruser")).click()
    await driver.findElement(By.id("remail")).click()
    assert(await driver.findElement(By.css(".help")).getText() == "El nombre de usuario es obligatorio")
    await driver.findElement(By.id("rpassword")).click()
    assert(await driver.findElement(By.css(".help:nth-child(10)")).getText() == "El email es obligatorio")
    await driver.findElement(By.id("ruser")).click()
    assert(await driver.findElement(By.css(".help:nth-child(15)")).getText() == "La contraseña es obligatoria")
    await driver.findElement(By.id("ruser")).sendKeys("aa")
    assert(await driver.findElement(By.css(".help:nth-child(5)")).getText() == "El nombre de usuario debe de tener al menos 4 caracteres")
    await driver.findElement(By.id("remail")).sendKeys("aaa")
    assert(await driver.findElement(By.css(".help:nth-child(10)")).getText() == "Debe de ser un email")
    await driver.findElement(By.id("rpassword")).sendKeys("usu")
    assert(await driver.findElement(By.css(".help:nth-child(15)")).getText() == "La contraseña debe de tener al menos 6 caracteres")
    await driver.findElement(By.id("ruser")).sendKeys("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
    assert(await driver.findElement(By.css(".help:nth-child(5)")).getText() == "El nombre de usuario no puede exceder los 30 caracteres")
    await driver.findElement(By.id("remail")).sendKeys("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@gmail.com")
    assert(await driver.findElement(By.css(".help:nth-child(10)")).getText() == "El email no puede exceder los 40 caracteres")
    await driver.findElement(By.id("rpassword")).sendKeys("usuario")
    {
      const elements = await driver.findElements(By.css(".help:nth-child(15)"))
      assert(!elements.length)
    }
    await driver.findElement(By.css(".submit:nth-child(15)")).click()
    assert(await driver.getTitle() == "Log-In / RecipeVault")
    await driver.findElement(By.id("remail")).clear()
    await driver.findElement(By.id("remail")).sendKeys("aaaaaa@gmail.com")
    await driver.executeScript("arguments[0].dispatchEvent(new Event('input', { bubbles: true }))", await driver.findElement(By.id("remail")));
    {
      const elements = await driver.findElements(By.css(".help:nth-child(10)"))
      assert(!elements.length)
    }
    await driver.findElement(By.id("ruser")).clear()
    await driver.findElement(By.id("ruser")).sendKeys("userr")
    await driver.executeScript("arguments[0].dispatchEvent(new Event('input', { bubbles: true }))", await driver.findElement(By.id("ruser")));
    {
      const elements = await driver.findElements(By.css(".help:nth-child(5)"))
      assert(!elements.length)
    }
  })
  //test de sign-up con usuario repetido
  it('Sign-up con correo repetido', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1181, height: 897 })
    assert(await driver.getTitle() == "Log-In / RecipeVault")
    await driver.findElement(By.id("ruser")).click()
    await driver.findElement(By.id("ruser")).sendKeys("usuario99")
    await driver.findElement(By.id("remail")).click()
    await driver.findElement(By.id("remail")).sendKeys("elena.sanchez@test.com")
    await driver.findElement(By.id("rpassword")).click()
    await driver.findElement(By.id("rpassword")).sendKeys("usuario")
    await driver.findElement(By.css(".submit:nth-child(13)")).click()
    assert(await driver.findElement(By.css(".error-message")).getText() == "El nombre de usuario o email ya se han utilizado anteriormente")
    assert(await driver.getTitle() == "Log-In / RecipeVault")
  })
  //test de sign-up con usuario repetido
  it('Sign-up con usuario repetido', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1181, height: 897 })
    assert(await driver.getTitle() == "Log-In / RecipeVault")
    await driver.findElement(By.id("ruser")).click()
    await driver.findElement(By.id("ruser")).sendKeys("ChefElenaES")
    await driver.findElement(By.id("remail")).click()
    await driver.findElement(By.id("remail")).sendKeys("usuario99@gmail.com")
    await driver.findElement(By.id("rpassword")).click()
    await driver.findElement(By.id("rpassword")).sendKeys("usuario")
    await driver.findElement(By.css(".submit:nth-child(13)")).click()
    assert(await driver.findElement(By.css(".error-message")).getText() == "El nombre de usuario o email ya se han utilizado anteriormente")
    assert(await driver.getTitle() == "Log-In / RecipeVault")
  })
})