// Generated by Selenium IDE
import { Builder, By, Key, until, WebDriver } from 'selenium-webdriver';
import assert from 'assert';
import Mocha from 'mocha';
import firefox from 'selenium-webdriver/firefox.js';
import { Select } from 'selenium-webdriver/lib/select.js'

async function selectByText(
  driver: WebDriver,
  selectLocator: By,
  text: string
) {
  const selectEl = await driver.wait(
    until.elementLocated(selectLocator),
    20000
  )
  const select = new Select(selectEl)
  await select.selectByVisibleText(text)
}

describe('Saved', function(this: Mocha.Suite) {
  this.timeout(600000)
  let driver: WebDriver
  let vars

  const options = new firefox.Options();
  options.addArguments('-headless');

  beforeEach(async function() {
    driver = await new Builder()
    .forBrowser('firefox')
    .setFirefoxOptions(options)
    .build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })

  it('Guardar y dejar de guardar', async function() {
    await driver.get("http://localhost:5173/login")
    await driver.manage().window().setRect({ width: 1500, height: 905 })
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("elena.sanchez@test.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("Password123!")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    await driver.findElement(By.css(".boton-panel:nth-child(5)")).click()
    assert(await driver.findElement(By.css(".section-title")).getText() == "Recetas guardadas")
    const p = await driver.wait(
    until.elementLocated(By.css("p:nth-child(1)")),
    20000
    )

    await driver.wait(
    until.elementTextIs(
        p,
        "No has guardado ninguna receta. ¡Guarda una!"
    ),
    20000
    )

    assert.strictEqual(
    await p.getText(),
    "No has guardado ninguna receta. ¡Guarda una!"
    )
    await driver.get("http://localhost:5173/recipe/000000000000000000000022")
    const h2 = await driver.wait(
      until.elementLocated(By.css("h2")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(h2),
      20000
    )
    assert(await driver.findElement(By.css("h2")).getText() == "Pasta Cacio e Pepe")
    {
      const elements = await driver.findElements(By.css(".post-save-button-inner > .lucide"))
      assert(elements.length)
    }
    await driver.findElement(By.css(".post-save-button-inner > .lucide")).click()
    await driver.findElement(By.css(".boton-panel:nth-child(5)")).click()
    {
      const elements = await driver.findElements(By.css(".tarjeta"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".post-title")).getText() == "Pasta Cacio e Pepe")
    await driver.get("http://localhost:5173/recipe/000000000000000000000022")
    const h21 = await driver.wait(
      until.elementLocated(By.css("h2")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(h21),
      20000
    )
    await driver.findElement(By.css(".lucide-bookmark-check")).click()
    await driver.findElement(By.css(".boton-panel:nth-child(5)")).click()
    assert(await driver.findElement(By.css("p:nth-child(1)")).getText() == "No has guardado ninguna receta. ¡Guarda una!")
    {
      const elements = await driver.findElements(By.css(".tarjeta"))
      assert(!elements.length)
    }
  })

})