// Generated by Selenium IDE
import { Builder, By, Key, until, WebDriver } from 'selenium-webdriver';
import assert from 'assert';
import Mocha from 'mocha';
import firefox from 'selenium-webdriver/firefox.js';
import { Select } from 'selenium-webdriver/lib/select.js'

async function selectByText(
  driver: WebDriver,
  selectLocator: By,
  text: string
) {
  const selectEl = await driver.wait(
    until.elementLocated(selectLocator),
    20000
  )
  const select = new Select(selectEl)
  await select.selectByVisibleText(text)
}

describe('Search', function(this: Mocha.Suite) {
  this.timeout(600000)
  let driver: WebDriver
  let vars

  const options = new firefox.Options();
  options.addArguments('-headless');

  beforeEach(async function() {
    driver = await new Builder()
    .forBrowser('firefox')
    .setFirefoxOptions(options)
    .build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })

  it('Búsqueda de recetas', async function() {
    await driver.get("http://localhost:5173/login")
    await driver.manage().window().setRect({ width: 1500, height: 1000 })
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("elena.sanchez@test.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("Password123!")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    await driver.findElement(By.css(".boton-panel:nth-child(2)")).click()
    await driver.findElement(By.css("input")).click()
    await driver.findElement(By.css("input")).sendKeys("gazpacho")
    await driver.findElement(By.css("input")).sendKeys(Key.ENTER)
    

    const text = await driver.executeScript(
      "return arguments[0].textContent",
      await driver.findElement(By.css(".results-count"))
    ) as string

    assert.strictEqual(text.trim(), "1 receta encontrada")
    {
      const elements = await driver.findElements(By.css(".tarjeta"))
      assert(elements.length)
    }
    const title = await driver.executeScript(
          "return arguments[0].textContent",
          await driver.findElement(By.css(".post-title"))
        ) as string
    
        assert.strictEqual(title.trim(), "Gazpacho Andaluz")
    await driver.findElement(By.css(".post-title")).click()
    const h2 = await driver.wait(
      until.elementLocated(By.css("h2")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(h2),
      20000
    )
    assert(await driver.findElement(By.css("h2")).getText() == "Gazpacho Andaluz")
    await driver.get("http://localhost:5173/search")
    {
      const elements = await driver.findElements(By.css(".tarjeta"))
      assert(!elements.length)
    }

    const recentTags = await driver.findElements(By.css(".recent-search-tag"))
    if (recentTags.length > 0) {
     await recentTags[0].click()
     const text1 = await driver.executeScript(
     "return arguments[0].textContent",
     await driver.findElement(By.css(".results-count"))
     ) as string
     assert.strictEqual(text1.trim(), "1 receta encontrada")
    }

   // await driver.findElement(By.css(".recent-search-tag")).click()
    //const text1 = await driver.executeScript(  /////////////////////
   //   "return arguments[0].textContent",
   //   await driver.findElement(By.css(".results-count"))
   // ) as string

    assert.strictEqual(text1.trim(), "1 receta encontrada")
    {
      const elements = await driver.findElements(By.css(".tarjeta"))
      assert(elements.length)
    }
    const title1 = await driver.executeScript(
          "return arguments[0].textContent",
          await driver.findElement(By.css(".post-title"))
        ) as string
    
        assert.strictEqual(title1.trim(), "Gazpacho Andaluz")
    await driver.findElement(By.css(".lucide-chevron-down")).click()
    await driver.findElement(By.css(".lucide-chevron-up > path")).click()
    assert(await driver.findElement(By.css(".advanced-filter-summary")).getText() == "No filters")
    await driver.findElement(By.css(".lucide-chevron-down > path")).click()
    console.log(1)
    {
      const elements = await driver.findElements(By.css(".advanced-filter-summary"))
      assert(!elements.length)
    }
    await driver.findElement(By.css(".advanced-input-group:nth-child(1) .lucide")).click()
    {
      const elements = await driver.findElements(By.css(".filter-modal"))
      assert(elements.length)
    }
    await driver.findElement(By.css(".lucide-x")).click()
    {
      const elements = await driver.findElements(By.css(".filter-modal"))
      assert(!elements.length)
    }
    await driver.findElement(By.css(".advanced-input-group:nth-child(1) .plus-button")).click()
    assert(await driver.findElement(By.css(".modal-header > h3")).getText() == "Añadir Ingredientes")
    {
      const elements = await driver.findElements(By.css(".select-option-tag:nth-child(1)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".select-option-tag:nth-child(2)"))
      assert(elements.length)
    }
    await driver.findElement(By.css(".select-option-tag:nth-child(1)")).click()
    {
      const elements = await driver.findElements(By.css(".filter-modal"))
      assert(!elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".selected-enum-tag"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".selected-enum-tag > button"))
      assert(elements.length)
    }
    await driver.findElement(By.css(".selected-enum-tag > button")).click()
    {
      const elements = await driver.findElements(By.css(".selected-enum-tag"))
      assert(!elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".selected-enum-tag > button"))
      assert(!elements.length)
    }
    await driver.findElement(By.css(".advanced-input-group:nth-child(1) .lucide")).click()
    await driver.findElement(By.css(".select-option-tag:nth-child(1)")).click()
    await driver.findElement(By.css(".plus-button:nth-child(2)")).click()
    await driver.findElement(By.css(".select-option-tag:nth-child(1)")).click()
    {
      const elements = await driver.findElements(By.css(".selected-enum-tag:nth-child(2)"))
      assert(elements.length)
    }
    await driver.findElement(By.css(".final-search-button")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    assert(await driver.findElement(By.css(".advanced-filter-summary")).getText() == "2 Ing.")
    const text2 = await driver.executeScript(
      "return arguments[0].textContent",
      await driver.findElement(By.css(".results-count"))
    ) as string

    assert.strictEqual(text2.trim(), "0 recetas encontradas")
    assert(await driver.findElement(By.css("p:nth-child(1)")).getText() == "No se han encontrado recetas con esos criterios.")
    {
      const elements = await driver.findElements(By.css(".no-results-box"))
      assert(elements.length)
    }
    await driver.get("http://localhost:5173/search")
    const h1 = await driver.wait(
      until.elementLocated(By.css(".section-title")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(h1),
      20000
    )
    await driver.findElement(By.css(".lucide-chevron-down")).click()
    console.log(1)
    await driver.findElement(By.css(".advanced-input-group:nth-child(1) .lucide")).click()
    await driver.findElement(By.css(".select-option-tag:nth-child(1)")).click()
    await driver.findElement(By.css(".final-search-button")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    const text3 = await driver.executeScript(
      "return arguments[0].textContent",
      await driver.findElement(By.css(".results-count"))
    ) as string

    assert.strictEqual(text3.trim(), "1 receta encontrada")
    const title2 = await driver.executeScript(
          "return arguments[0].textContent",
          await driver.findElement(By.css(".post-title"))
        ) as string
    
        assert.strictEqual(title2.trim(), "Croissant Casero")
    await driver.findElement(By.css(".post-title")).click()
    const ing = await driver.wait(
      until.elementLocated(By.css(".IngredientesReceta li:nth-child(1)")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(ing),
      20000
    )
    assert(await driver.findElement(By.css(".IngredientesReceta li:nth-child(1)")).getText() == "harina: 500g")
    console.log(1)
    await driver.get("http://localhost:5173/search")
    const lucide = await driver.wait(
      until.elementLocated(By.css(".lucide-chevron-down")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(lucide),
      20000
    )
    await driver.findElement(By.css(".lucide-chevron-down")).click()
    await driver.findElement(By.css(".advanced-input-group:nth-child(2) .plus-button")).click()
    await driver.findElement(By.css(".select-option-tag:nth-child(7)")).click()
    await driver.findElement(By.css(".final-search-button")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    const text4 = await driver.executeScript(
      "return arguments[0].textContent",
      await driver.findElement(By.css(".results-count"))
    ) as string

    assert.strictEqual(text4.trim(), "1 receta encontrada")
    {
      const elements = await driver.findElements(By.css(".category-tag:nth-child(1)"))
      assert(elements.length)
    }
    await driver.findElement(By.css(".lucide-chevron-down")).click()
    await driver.findElement(By.css(".lucide-x")).click()
    await driver.findElement(By.css(".advanced-input-group:nth-child(3) .plus-button")).click()
    await driver.findElement(By.css(".select-option-tag:nth-child(1)")).click()
    await driver.findElement(By.css(".final-search-button")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    const text5 = await driver.executeScript(
      "return arguments[0].textContent",
      await driver.findElement(By.css(".results-count"))
    ) as string

    assert.strictEqual(text5.trim(), "4 recetas encontradas")
    {
      const elements = await driver.findElements(By.css(".tarjeta:nth-child(1)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".tarjeta:nth-child(2)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".tarjeta:nth-child(3)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".tarjeta:nth-child(4)"))
      assert(elements.length)
    }
    await driver.findElement(By.css(".tarjeta:nth-child(1) .post-title")).click()
    console.log(2)
    await driver.executeScript("window.scrollTo(0,100)")
    const ut = await driver.wait(
      until.elementLocated(By.css(".UtensiliosReceta li:nth-child(1)")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(ut),
      20000
    )
    console.log(3)
    assert(await driver.findElement(By.css(".UtensiliosReceta li:nth-child(1)")).getText() == "cuchillo")
    await driver.get("http://localhost:5173/search")
    const lucide1 = await driver.wait(
      until.elementLocated(By.css(".lucide-chevron-down")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(lucide1),
      20000
    )
    await driver.findElement(By.css(".lucide-chevron-down")).click()
    await driver.findElement(By.css(".advanced-input-group:nth-child(2) .lucide")).click()
    await driver.findElement(By.css(".select-option-tag:nth-child(8)")).click()
    await driver.findElement(By.css(".advanced-input-group:nth-child(1) .lucide")).click()
    await driver.findElement(By.css(".select-option-tag:nth-child(7)")).click()
    await driver.findElement(By.css(".plus-button:nth-child(1)")).click()
    await driver.findElement(By.css(".select-option-tag:nth-child(1)")).click()
    await driver.findElement(By.css(".final-search-button")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    const text6 = await driver.executeScript(
      "return arguments[0].textContent",
      await driver.findElement(By.css(".results-count"))
    ) as string

    assert.strictEqual(text6.trim(), "1 receta encontrada")
    const title3 = await driver.executeScript(
          "return arguments[0].textContent",
          await driver.findElement(By.css(".post-title"))
        ) as string
    
        assert.strictEqual(title3.trim(), "Gazpacho Andaluz")
    await driver.findElement(By.css(".post-title")).click()
    const h21 = await driver.wait(
      until.elementLocated(By.css("h2")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(h21),
      20000
    )
    {
      const elements = await driver.findElements(By.css(".category-tag:nth-child(2)"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".IngredientesReceta li:nth-child(1)")).getText() == "aceite: 100ml")
    assert(await driver.findElement(By.css(".UtensiliosReceta li:nth-child(1)")).getText() == "cuchillo")
  })

  it('Búsqueda de usuarios', async function() {
    await driver.get("http://localhost:5173/login")
    await driver.manage().window().setRect({ width: 1181, height: 929 })
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("elena.sanchez@test.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("Password123!")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    await driver.findElement(By.css(".boton-panel:nth-child(2) > span")).click()
    await driver.findElement(By.css(".mode-tab:nth-child(2)")).click()
    {
      const elements = await driver.findElements(By.css(".user-social-card:nth-child(1)"))
      assert(!elements.length)
    }
    await driver.findElement(By.css("input")).click()
    await driver.findElement(By.css("input")).sendKeys("c")
    await driver.findElement(By.css(".final-search-button")).click()
    {
      const elements = await driver.findElements(By.css(".user-social-card:nth-child(1)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".user-social-card:nth-child(2)"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".user-social-card:nth-child(1) .user-card-username")).getText() == "@AndeanCooking")
    assert(await driver.findElement(By.css(".user-social-card:nth-child(2) .user-card-username")).getText() == "@CanadianPantry")
    await driver.findElement(By.css(".user-social-card:nth-child(1) .view-profile-button")).click()
    {
      const elements = await driver.findElements(By.css("h1"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css("h3:nth-child(1)")).getText() == "AndeanCooking")
    await driver.findElement(By.css(".boton-panel:nth-child(2)")).click()
    await driver.findElement(By.css(".mode-tab:nth-child(2)")).click()
    await driver.findElement(By.css("input")).click()
    await driver.findElement(By.css("input")).sendKeys("jdhnfndsjh")
    await driver.findElement(By.css(".final-search-button")).click()
    {
      const elements = await driver.findElements(By.css(".user-social-card:nth-child(1)"))
      assert(!elements.length)
    }
  })
})