// Generated by Selenium IDE
import { Builder, By, Key, until, WebDriver } from 'selenium-webdriver';
import assert from 'assert';
import Mocha from 'mocha';
import firefox from 'selenium-webdriver/firefox.js';
import { Select } from 'selenium-webdriver/lib/select.js'

async function selectByText(
  driver: WebDriver,
  selectLocator: By,
  text: string
) {
  const selectEl = await driver.wait(
    until.elementLocated(selectLocator),
    20000
  )
  const select = new Select(selectEl)
  await select.selectByVisibleText(text)
}

describe('Search', function(this: Mocha.Suite) {
  this.timeout(600000)
  let driver: WebDriver
  let vars

  const options = new firefox.Options();
  options.addArguments('-headless');

  beforeEach(async function() {
    driver = await new Builder()
    .forBrowser('firefox')
    .setFirefoxOptions(options)
    .build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })

  it('Búsqueda de recetas', async function () {
    await driver.get("http://localhost:5173/login")
    await driver.manage().window().setRect({ width: 1500, height: 1000 })

    // Login
    const emailInput = await driver.wait(until.elementLocated(By.id("lemail")), 20000)
    await emailInput.sendKeys("elena.sanchez@test.com")

    const passwordInput = await driver.wait(until.elementLocated(By.id("lpassword")), 20000)
    await passwordInput.sendKeys("Password123!")

    const submitBtn = await driver.wait(until.elementLocated(By.css(".submit")), 20000)
    await submitBtn.click()

    // Esperar a que el login termine (navegación real)
    await driver.wait(until.urlContains("localhost:5173"), 20000)

    // Ir DIRECTAMENTE a Search (evita flakiness)
    //await driver.get("http://localhost:5173/search")
    await driver.findElement(By.css(".boton-panel:nth-child(2)")).click()

    // Esperar a que la vista Search esté renderizada (me cargado)
    await driver.wait(
      until.elementLocated(By.xpath("//h2[text()='Búsqueda']")),
      20000
    )

    // Buscar "gazpacho"
    const searchInput = await driver.wait(
      until.elementLocated(By.css(".search-bar-main input")),
      20000
    )
    await driver.wait(until.elementIsVisible(searchInput), 20000)
    await searchInput.clear()
    await searchInput.sendKeys("gazpacho", Key.ENTER)

    // Esperar resultados
    const resultsCount = await driver.wait(
      until.elementLocated(By.css(".results-count")),
      20000
    )
    await driver.wait(until.elementIsVisible(resultsCount), 20000)
    let text = await resultsCount.getText()
    assert.strictEqual(text.trim(), "1 receta encontrada")

    const cards = await driver.findElements(By.css(".tarjeta"))
    assert(cards.length > 0)

    const title = await driver.findElement(By.css(".post-title")).getText()
    assert.strictEqual(title.trim(), "Gazpacho Andaluz")

    // Abrir receta
    await driver.findElement(By.css(".post-title")).click()
    const h2 = await driver.wait(until.elementLocated(By.css("h2")), 20000)
    await driver.wait(until.elementIsVisible(h2), 20000)
    assert.strictEqual(await h2.getText(), "Gazpacho Andaluz")

    // Volver a búsqueda
    await driver.get("http://localhost:5173/search")

    await driver.wait(
      until.elementLocated(By.xpath("//h2[text()='Búsqueda']")),
      20000
    )

    let tarjetas = await driver.findElements(By.css(".tarjeta"))
    assert.strictEqual(tarjetas.length, 0)

    // Click en búsqueda reciente si existe
    const recentTags = await driver.findElements(By.css(".recent-search-tag"))
    if (recentTags.length > 0) {
      await recentTags[0].click()

      const resultsCountRecent = await driver.wait(
        until.elementLocated(By.css(".results-count")),
        20000
      )
    await driver.wait(until.elementIsVisible(resultsCountRecent), 20000)

    text = await resultsCountRecent.getText()
    assert.strictEqual(text.trim(), "1 receta encontrada")
  }

  // Abrir búsqueda avanzada
    const advancedBtn = await driver.wait(
      until.elementLocated(By.css(".advanced-search-header")),
      20000
    )
    await advancedBtn.click()

    const firstIngredientBtn = await driver.wait(
      until.elementLocated(By.css(".advanced-input-group .plus-button")),
      20000
    )
    await firstIngredientBtn.click()
    const ingredientOption = await driver.wait(
      until.elementLocated(By.css(".select-option-tag")),
      20000
    )
    await ingredientOption.click()
    const finalSearchBtn = await driver.wait(
      until.elementLocated(By.css(".final-search-button")),
      20000
    )
    await finalSearchBtn.click()
    const resultsCountFiltered = await driver.wait(
      until.elementLocated(By.css(".results-count")),
      20000
    )
    await driver.wait(until.elementIsVisible(resultsCountFiltered), 20000)
    text = await resultsCountFiltered.getText()
    assert.strictEqual(text.trim(), "0 recetas encontradas")
  })




  it('Búsqueda de usuarios', async function() {
    await driver.get("http://localhost:5173/login")
    await driver.manage().window().setRect({ width: 1181, height: 929 })
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("elena.sanchez@test.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("Password123!")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    await driver.findElement(By.css(".boton-panel:nth-child(2) > span")).click()
    await driver.findElement(By.css(".mode-tab:nth-child(2)")).click()
    {
      const elements = await driver.findElements(By.css(".user-social-card:nth-child(1)"))
      assert(!elements.length)
    }
    await driver.findElement(By.css("input")).click()
    await driver.findElement(By.css("input")).sendKeys("c")
    await driver.findElement(By.css(".final-search-button")).click()
    {
      const elements = await driver.findElements(By.css(".user-social-card:nth-child(1)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".user-social-card:nth-child(2)"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".user-social-card:nth-child(1) .user-card-username")).getText() == "@AndeanCooking")
    assert(await driver.findElement(By.css(".user-social-card:nth-child(2) .user-card-username")).getText() == "@CanadianPantry")
    await driver.findElement(By.css(".user-social-card:nth-child(1) .view-profile-button")).click()
    {
      const elements = await driver.findElements(By.css("h1"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css("h3:nth-child(1)")).getText() == "AndeanCooking")
    await driver.findElement(By.css(".boton-panel:nth-child(2)")).click()
    await driver.findElement(By.css(".mode-tab:nth-child(2)")).click()
    await driver.findElement(By.css("input")).click()
    await driver.findElement(By.css("input")).sendKeys("jdhnfndsjh")
    await driver.findElement(By.css(".final-search-button")).click()
    {
      const elements = await driver.findElements(By.css(".user-social-card:nth-child(1)"))
      assert(!elements.length)
    }
  })
})