// Generated by Selenium IDE
import { Builder, By, Key, until, WebDriver } from 'selenium-webdriver';
import assert from 'assert';
import Mocha from 'mocha';
import firefox from 'selenium-webdriver/firefox.js';
import { Select } from 'selenium-webdriver/lib/select.js'

async function selectByText(
  driver: WebDriver,
  selectLocator: By,
  text: string
) {
  const selectEl = await driver.wait(
    until.elementLocated(selectLocator),
    20000
  )
  const select = new Select(selectEl)
  await select.selectByVisibleText(text)
}

async function clickNthButtonInContainer(
  driver: WebDriver,
  containerCss: string,
  index: number
) {
  const buttons = await driver.wait(
    until.elementsLocated(By.css(`${containerCss} button`)),
    20000
  )

  await driver.wait(
    until.elementIsVisible(buttons[index]),
    20000
  )

  await buttons[index].click()
}


describe('User', function(this: Mocha.Suite) {
  this.timeout(600000)
  let driver: WebDriver,
  index: number,
  containerSelector: string

  const options = new firefox.Options();
  options.addArguments('-headless');

  beforeEach(async function() {
    driver = await new Builder()
    .forBrowser('firefox')
    .setFirefoxOptions(options)
    .build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })

  it('Renderización perfil ajeno', async function() {
    await driver.get("http://localhost:5173/login")
    await driver.manage().window().setRect({ width: 1181, height: 906 })
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("elena.sanchez@test.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("Password123!")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    await driver.get("http://localhost:5173/user/000000000000000000000002")
    const foto = await driver.wait(
      until.elementLocated(By.css(".foto-perfil")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(foto),
      20000
    )
    {
      const elements = await driver.findElements(By.css(".foto-perfil"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css("h3:nth-child(1)")).getText() == "ItalianoCucina")
    {
      const elements = await driver.findElements(By.css(".botonFollow"))
      assert(elements.length)
    }
    //assert(await driver.findElement(By.css("p:nth-child(2)")).getText() == "La verdadera cocina del sur de Italia.")
    const bio = await driver.wait(
    until.elementLocated(By.css(".user-description")),
    20000
    )
    assert.strictEqual(await bio.getText(), "La verdadera cocina del sur de Italia.")
    // lo nuevo (arriba)
    // assert(await driver.findElement(By.css("a:nth-child(1) > p")).getText() == "Seguidores: 0")
    // assert(await driver.findElement(By.css("a:nth-child(2) > p")).getText() == "Seguidos: 0")
    const stats = await driver.wait(
      until.elementsLocated(By.css(".user-stats p")),
      20000
    )

    const texts = await Promise.all(stats.map(e => e.getText()))

    assert(texts.includes("Seguidores: 0"))
    assert(texts.includes("Seguidos: 0"))

    {
      const elements = await driver.findElements(By.css(".post-card"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".post-user-name")).getText() == "ItalianoCucina")
    assert(await driver.findElement(By.css(".post-title")).getText() == "Pasta Cacio e Pepe")
  })
  it('Creación y borrado de perfil', async function() {
    await driver.get("http://localhost:5173/login")
    await driver.manage().window().setRect({ width: 1181, height: 912 })
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("usuario50@gmail.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("usuario")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    assert(await driver.findElement(By.css(".error-message")).getText() == "El usuario o la contraseña son incorrectos")
    await driver.findElement(By.id("ruser")).click()
    await driver.findElement(By.id("ruser")).sendKeys("usuario50")
    await driver.findElement(By.id("remail")).click()
    await driver.findElement(By.id("remail")).sendKeys("usuario50@gmail.com")
    await driver.findElement(By.id("rpassword")).click()
    await driver.findElement(By.id("rpassword")).sendKeys("usuario")
    await driver.findElement(By.css(".submit:nth-child(13)")).click()
    const usrnm = await driver.wait(
      until.elementLocated(By.css(".user-name")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(usrnm),
      20000
    )
    assert(await driver.findElement(By.css(".user-name")).getText() == "usuario50")
    await driver.findElement(By.css(".logout")).click()
    const input = await driver.wait(
      until.elementLocated(By.id("lemail")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(input),
      20000
    )
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("usuario50@gmail.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("usuario")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    assert(await driver.findElement(By.css(".user-name")).getText() == "usuario50")
   // await driver.findElement(By.css(".boton-panel:nth-child(3)")).click()
    const panelButtons = await driver.wait(
      until.elementsLocated(By.css(".boton-panel")),
      20000
    )
    await panelButtons[2].click()

    assert(await driver.findElement(By.css(".posts-grid > p")).getText() == "Este usuario no ha compartido ninguna receta todavía.")
    //await driver.findElement(By.css(".datosUsuario button:nth-child(3)")).click()
    
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("usuario50@gmail.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("usuario")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    assert(await driver.findElement(By.css(".error-message")).getText() == "El usuario o la contraseña son incorrectos")
  })
  it('Edición de perfil correcta', async function() {
    await driver.get("http://localhost:5173/login")
    await driver.manage().window().setRect({ width: 1181, height: 906 })
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("elena.sanchez@test.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("Password123!")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    //await driver.findElement(By.css(".boton-panel:nth-child(3)")).click()
    const panelButtons = await driver.wait(
     until.elementsLocated(By.css(".boton-panel")),
     20000
    )
    await panelButtons[2].click()

    const foto = await driver.wait(
      until.elementLocated(By.css(".foto-perfil")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(foto),
      20000
    )
    {
      const elements = await driver.findElements(By.css(".user-profile-info"))
      assert(!elements.length)
    }
    //assert(await driver.findElement(By.css("h3:nth-child(1)")).getText() == "ChefElenaES")
    //assert(await driver.findElement(By.css("p:nth-child(2)")).getText() == "Especialista en tapas y arroces.")
    const username = await driver.wait(
     until.elementLocated(By.css("h3")),
     20000
    )
    await driver.wait(until.elementIsVisible(username), 20000)
    assert.strictEqual(await username.getText(), "ChefElenaES")

    const bio = await driver.wait(
    until.elementLocated(By.css(".user-description")),
    20000
    )
    assert.strictEqual(await bio.getText(), "Especialista en tapas y arroces.")
    //lo nuevo (arriba)
    {
      const elements = await driver.findElements(By.css(".post-card"))
      assert(elements.length)
    }
    const button = await driver.wait(
      until.elementLocated(By.css(".datosUsuario button:nth-child(2)")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(button),
      20000
    )
    //await driver.findElement(By.css(".datosUsuario button:nth-child(2)")).click()
    await clickNthButtonInContainer(driver, ".datosUsuario", 1)
    assert(await driver.findElement(By.css("div:nth-child(1) > label")).getText() == "Nombre de usuario:")
    assert(await driver.findElement(By.css("div:nth-child(2) > label")).getText() == "Email:")
    assert(await driver.findElement(By.css("div:nth-child(3) > label")).getText() == "Biografía:")
    {
      //const elements = await driver.findElements(By.css(".editButton:nth-child(1)"))
      //assert(elements.length)
      const editButtons = await driver.wait(
       until.elementsLocated(By.css(".editButton")),
       20000
      )
      await editButtons[0].click()

    }
    {
     const editButtons = await driver.wait(
     until.elementsLocated(By.css(".editButton")),
     20000
    )
    await editButtons[1].click()
    }
    await driver.findElement(By.name("username")).click()
    await driver.findElement(By.name("username")).sendKeys("ChefElenaESA")
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("elenaa.sanchez@test.com")
    await driver.findElement(By.name("bio")).click()
    await driver.findElement(By.name("bio")).sendKeys("Especialista en tapas y arroces.A")
    //await driver.findElement(By.css(".editButton:nth-child(2)")).click()
    await clickNthButtonInContainer(driver, ".datosUsuario", 1)
    assert(await driver.findElement(By.css("h3:nth-child(1)")).getText() == "ChefElenaES")
    assert(await driver.findElement(By.css("p:nth-child(2)")).getText() == "Especialista en tapas y arroces.")
    await driver.findElement(By.css(".datosUsuario button:nth-child(2)")).click()
    await driver.findElement(By.name("username")).click()
    await driver.findElement(By.name("username")).clear()
    await driver.findElement(By.name("username")).sendKeys("ChefElenaESA")
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).clear()
    await driver.findElement(By.name("email")).sendKeys("elenaa.sanchez@test.com")
    await driver.findElement(By.name("bio")).click()
    await driver.findElement(By.name("bio")).clear()
    await driver.findElement(By.name("bio")).sendKeys("Especialista en tapas y arroces.A")
   // await driver.findElement(By.css(".editButton:nth-child(1)")).click()
   const editButtons = await driver.wait(
   until.elementsLocated(By.css(".editButton")),
   20000
   )
   await editButtons[0].click()

    const h3 = await driver.wait(
      until.elementLocated(By.css("h3:nth-child(1)")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(h3),
      20000
    )
    assert(await driver.findElement(By.css("h3:nth-child(1)")).getText() == "ChefElenaESA")
    assert(await driver.findElement(By.css("p:nth-child(2)")).getText() == "Especialista en tapas y arroces.A")
    assert(await driver.findElement(By.css(".post-user-name")).getText() == "ChefElenaESA")
    await driver.findElement(By.css(".logout")).click()
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("elenaa.sanchez@test.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("Password123!")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    assert(await driver.findElement(By.css(".user-name")).getText() == "ChefElenaESA")
    assert(await driver.findElement(By.css(".user-handle")).getText() == "@chefelenaesa")
    assert(await driver.findElement(By.css(".user-description")).getText() == "Especialista en tapas y arroces.A")
    //await driver.findElement(By.css(".boton-panel:nth-child(3)")).click()
    const boton = await driver.wait(
      until.elementLocated(By.css(".datosUsuario button:nth-child(2)")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(boton),
      20000
    )
   // await driver.findElement(By.css(".datosUsuario button:nth-child(2)")).click()
    await clickNthButtonInContainer(driver, ".datosUsuario", 1)
    await driver.findElement(By.name("username")).click()
    await driver.findElement(By.name("username")).clear()
    await driver.findElement(By.name("username")).sendKeys("ChefElenaES")
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).clear()
    await driver.findElement(By.name("email")).sendKeys("elena.sanchez@test.com")
    await driver.findElement(By.name("bio")).click()
    await driver.findElement(By.name("bio")).clear()
    await driver.findElement(By.name("bio")).sendKeys("Especialista en tapas y arroces.")
   // await driver.findElement(By.css(".editButton:nth-child(1)")).click()
    const editButton = await driver.wait(
    until.elementsLocated(By.css(".editButton")),
    20000
   )
   await editButton[0].click()

  })
  it('Edición de perfil incorrecta', async function() {
    await driver.get("http://localhost:5173/login")
    await driver.manage().window().setRect({ width: 1181, height: 906 })
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("elena.sanchez@test.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("Password123!")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    //const boton = await driver.wait(
    //  until.elementLocated(By.css(".boton-panel:nth-child(3)")),
    //  20000
    //)

    //await driver.wait(
    //  until.elementIsVisible(boton),
    //  20000
    //)
    const panelButtons = await driver.wait(
    until.elementsLocated(By.css(".boton-panel")),
    20000
    )
    await panelButtons[2].click()

    //await driver.findElement(By.css(".boton-panel:nth-child(3)")).click()
    //await driver.findElement(By.css(".datosUsuario button:nth-child(2)")).click()
    await clickNthButtonInContainer(driver, ".datosUsuario", 1)

    await driver.findElement(By.name("username")).click()
    await driver.findElement(By.name("username")).clear()
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).clear()
    await driver.findElement(By.css(".formulario-editar-usuario")).click()
    assert(await driver.findElement(By.css("div:nth-child(1) > .help")).getText() == "El nombre de usuario es obligatorio")
    assert(await driver.findElement(By.css("div:nth-child(2) > .help")).getText() == "El email es obligatorio")
    await driver.findElement(By.name("username")).click()
    await driver.findElement(By.name("username")).sendKeys("Che")
    assert(await driver.findElement(By.css("div:nth-child(1) > .help")).getText() == "El nombre de usuario debe tener al menos 4 caracteres")
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("aa")
    assert(await driver.findElement(By.css("div:nth-child(2) > .help")).getText() == "Email inválido")
    await driver.findElement(By.name("username")).click()
    await driver.findElement(By.name("username")).sendKeys("Chejnfdnjhfdnvbjfdkjhfdsbhjfdnbjfdfdjbhfdnfbjdbhjsdbdfjbd")
    assert(await driver.findElement(By.css("div:nth-child(1) > .help")).getText() == "El nombre de usuario no puede exceder los 30 caracteres")
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@gmail.com")
    assert(await driver.findElement(By.css("div:nth-child(2) > .help")).getText() == "El email no puede exceder los 40 caracteres")
    await driver.findElement(By.name("bio")).click()
    await driver.findElement(By.name("bio")).clear()
    await driver.findElement(By.name("bio")).sendKeys("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
    await driver.executeScript("arguments[0].dispatchEvent(new Event('input', { bubbles: true }))", await driver.findElement(By.name("bio")));
    await driver.findElement(By.css(".formulario-editar-usuario > div:nth-child(3)")).click()
    const help = await driver.wait(
      until.elementLocated(By.css(".help:nth-child(3)")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(help),
      20000
    )
    assert(await driver.findElement(By.css(".help:nth-child(3)")).getText() == "La bio no puede exceder los 200 caracteres")
    await driver.findElement(By.css(".editButton:nth-child(1)")).click()
    {
     // const elements = await driver.findElements(By.css(".editButton:nth-child(1)"))
     // assert(elements.length)
     const editButtons = await driver.wait(
     until.elementsLocated(By.css(".editButton")),
     20000
     )
    await editButtons[0].click()
    }
    await driver.findElement(By.name("username")).clear()
    await driver.findElement(By.name("username")).sendKeys("ChefElenaES")
    await driver.findElement(By.name("email")).clear()
    await driver.findElement(By.name("email")).sendKeys("elena.sanchez@test.com")
    await driver.findElement(By.name("bio")).clear()
    await driver.findElement(By.name("bio")).sendKeys("Reseña")
    
    {
      const elements = await driver.findElements(By.css("div:nth-child(1) > .help"))
      assert(!elements.length)
    }
    await driver.wait(async () => {
      const elements = await driver.findElements(By.css("div:nth-child(2) > .help"))
      return elements.length === 0
    }, 30000)
    {
      const elements = await driver.findElements(By.css("div:nth-child(2) > .help"))
      assert(!elements.length)
    }
    await driver.wait(async () => {
      const elements = await driver.findElements(By.css("div:nth-child(3) > .help"))
      return elements.length === 0
    }, 30000)
    {
      const elements = await driver.findElements(By.css("div:nth-child(3) > .help"))
      assert(!elements.length)
    }
  })
  it('Renderización perfil propio', async function() {
    await driver.get("http://localhost:5173/login")
    await driver.manage().window().setRect({ width: 1500, height: 906 })
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("elena.sanchez@test.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("Password123!")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    //await driver.findElement(By.css(".boton-panel:nth-child(3)")).click()
    const panelButtons = await driver.wait(
     until.elementsLocated(By.css(".boton-panel")),
     20000
    )
    await panelButtons[2].click()

    {
      const elements = await driver.findElements(By.css(".user-profile-info"))
      assert(!elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".foto-perfil"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css("h3:nth-child(1)")).getText() == "ChefElenaES")
    {
      const elements = await clickNthButtonInContainer(driver, ".datosUsuario", 1) //await driver.findElements(By.css(".datosUsuario button:nth-child(2)"))
      assert(elements.length)
    }
    {
      const elements = await clickNthButtonInContainer(driver, ".datosUsuario", 2) //await driver.findElements(By.css(".datosUsuario button:nth-child(3)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cambiar-foto > button"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css("p:nth-child(2)")).getText() == "Especialista en tapas y arroces.")
    assert(await driver.findElement(By.css("a:nth-child(1) > p")).getText() == "Seguidores: 0")
    assert(await driver.findElement(By.css("a:nth-child(2) > p")).getText() == "Seguidos: 0")
    {
      const elements = await driver.findElements(By.css(".post-card"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".post-user-name")).getText() == "ChefElenaES")
    const text3 = await driver.executeScript(
      "return arguments[0].textContent",
      await driver.findElement(By.css(".post-title"))
    ) as string

    assert.strictEqual(text3.trim(), "Gazpacho Andaluz")
  })
  it('Seguir y dejar de seguir', async function() {
    await driver.get("http://localhost:5173/login")
    await driver.manage().window().setRect({ width: 1181, height: 906 })
    await driver.findElement(By.id("lemail")).click()
    await driver.findElement(By.id("lemail")).sendKeys("elena.sanchez@test.com")
    await driver.findElement(By.id("lpassword")).click()
    await driver.findElement(By.id("lpassword")).sendKeys("Password123!")
    await driver.findElement(By.css(".submit:nth-child(9)")).click()
    await driver.get("http://localhost:5173/user/000000000000000000000002")
    const p = await driver.wait(
      until.elementLocated(By.css("a:nth-child(1) > p")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(p),
      20000
    )
    assert(await driver.findElement(By.css("a:nth-child(1) > p")).getText() == "Seguidores: 0")
    assert(await driver.findElement(By.css("div:nth-child(3) > .stat-number")).getText() == "0")
    await driver.findElement(By.css(".botonFollow")).click()
    assert(await driver.findElement(By.css("a:nth-child(1) > p")).getText() == "Seguidores: 1")
    assert(await driver.findElement(By.css("div:nth-child(3) > .stat-number")).getText() == "1")
    await driver.findElement(By.css("a:nth-child(1) strong")).click()
    const usr = await driver.wait(
      until.elementLocated(By.css(".usuario-item-card")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(usr),
      20000
    )
    {
      const elements = await driver.findElements(By.css(".usuario-item-card"))
      assert(elements.length)
    }
    const text = await driver.executeScript(
      "return arguments[0].textContent",
      await driver.findElement(By.css("h4"))
    ) as string

    assert.strictEqual(text.trim(), "ChefElenaES")
    assert(await driver.findElement(By.css(".section-title")).getText() == "Lista de ItalianoCucina")
    //await driver.findElement(By.css(".boton-follow-toggle:nth-child(2)")).click()
    const toggles = await driver.wait(
     until.elementsLocated(By.css(".boton-follow-toggle")),
     20000
    )
    await toggles[1].click()

    {
      const elements = await driver.findElements(By.css(".usuarioSimplificado"))
      assert(!elements.length)
    }
    await driver.findElement(By.css(".boton-panel:nth-child(3)")).click()
    assert(await driver.findElement(By.css("a:nth-child(1) > p")).getText() == "Seguidores: 0")
    assert(await driver.findElement(By.css("a:nth-child(2) > p")).getText() == "Seguidos: 1")
    await driver.findElement(By.css("a:nth-child(2) > p")).click()
    assert(await driver.findElement(By.css(".section-title")).getText() == "Lista de ChefElenaES")
    {
      const elements = await driver.findElements(By.css(".usuario-item-card"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css("h4")).getText() == "ItalianoCucina")
    {
      const elements = await driver.findElements(By.css(".botonFollow"))
      assert(elements.length)
    }
    //await driver.findElement(By.css(".boton-follow-toggle:nth-child(1)")).click()
    const toggle = await driver.wait(
    until.elementsLocated(By.css(".boton-follow-toggle")),
    20000
    )
    await toggle[1].click()

    {
      const elements = await driver.findElements(By.css(".active"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".boton-follow-toggle:nth-child(2)"))
      assert(elements.length)
    }
    await driver.findElement(By.css(".boton-follow-toggle:nth-child(2)")).click()
    await driver.findElement(By.css(".botonFollow")).click()
    {
      const elements = await driver.findElements(By.css(".usuario-item-card"))
      assert(!elements.length)
    }
    assert(await driver.findElement(By.css("div:nth-child(3) > .stat-number")).getText() == "0")
    await driver.get("http://localhost:5173/user/000000000000000000000002")
    const p1 = await driver.wait(
      until.elementLocated(By.css("a:nth-child(1) > p")),
      20000
    )

    await driver.wait(
      until.elementIsVisible(p1),
      20000
    )
    assert(await driver.findElement(By.css("a:nth-child(1) > p")).getText() == "Seguidores: 0")
    await driver.findElement(By.css(".botonFollow")).click()
    assert(await driver.findElement(By.css("a:nth-child(1) > p")).getText() == "Seguidores: 1")
    assert(await driver.findElement(By.css("div:nth-child(3) > .stat-number")).getText() == "1")
    await driver.findElement(By.css(".botonFollow")).click()
    assert(await driver.findElement(By.css("div:nth-child(3) > .stat-number")).getText() == "0")
    assert(await driver.findElement(By.css("a:nth-child(1) > p")).getText() == "Seguidores: 0")
  })

})