name: CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

env:
  MONGODB_URL: mongodb://127.0.0.1:27017/recipevault-db-test

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    services:
        mongodb:
          image: mongo:6
          ports:
            - 27017:27017
          options: >-
            --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
           node-version: "18"

      

       #Backend  

      - name: Install backend dependencies
        working-directory: server
        run: npm install

      - name: Run backend tests
        working-directory: server
        run: npm test

        #Frontend

      - name: Install frontend dependencies
        working-directory: client   
        run: npm install

   #   - name: Install jsdom for Vitest
   #     working-directory: client
   #     run: npm install jsdom
    

   #   - name: Run frontend unit tests
   #     working-directory: client
   #     run: npm test

      # e2e tests (Cypress)
      - name: Install Cypress and start-server-and-test
        working-directory: client
        run: |
          npm install cypress --save-dev
          npm install start-server-and-test --save-dev

      - name: Run Cypress E2E
        working-directory: client
        run: npx start-server-and-test dev http://localhost:5173 cypress:run
